# Generated by Django 3.2.7 on 2021-09-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='chief',
            new_name='chef',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='difficulty',
            field=models.CharField(choices=[('1', 'Iniciante'), ('2', 'Experiente'), ('3', 'Avançado')], default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='method',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='short_description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
